// IMPORTANT: THIS FILE IS AUTO GENERATED! DO NOT MANUALLY EDIT OR CHECKIN!
export const VERSION = {
  dirty: true,
  raw: '7dcafff-dirty',
  hash: '7dcafff',
  distance: null,
  tag: null,
  semver: null,
  suffix: '7dcafff-dirty',
  semverString: null,
  version: {
    name: 'leaflet-angular',
    version: '4.0.82',
    license: 'MIT',
    scripts: {
      ng: 'ng',
      start: 'ng serve',
      build:
        'npm version patch && node ./replace.build.js && node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build — prod — base-href /llc/ && node ./versioning.build.js',
      test: 'ng test',
      lint: 'ng lint',
      e2e: 'ng e2e',
      'build-prod-patch':
        'npm version patch && node ./replace.build.js && ng build --prod --base-href=./ && node ./versioning.build.js',
    },
    private: true,
    dependencies: {
      '@angular/animations': '^7.1.4',
      '@angular/cdk': '^7.2.0',
      '@angular/common': '^7.1.4',
      '@angular/compiler': '^7.1.4',
      '@angular/core': '^7.1.4',
      '@angular/flex-layout': '^7.0.0-beta.22',
      '@angular/forms': '^7.1.4',
      '@angular/http': '^7.1.4',
      '@angular/material': '^7.2.0',
      '@angular/platform-browser': '^7.1.4',
      '@angular/platform-browser-dynamic': '^7.1.4',
      '@angular/router': '^7.1.4',
      '@ckeditor/ckeditor5-build-classic': '^12.1.0',
      '@ckeditor/ckeditor5-editor-classic': '^12.1.0',
      '@ngx-translate/core': '^11.0.1',
      '@ngx-translate/http-loader': '^4.0.0',
      '@swimlane/ngx-charts': '^10.0.0',
      '@swimlane/ngx-datatable': '^14.0.0',
      'angular-svg-icon': '^7.0.1',
      'chart.js': '^2.7.3',
      'core-js': '^2.6.1',
      hammerjs: '^2.0.8',
      'highlight.js': '9.13.1',
      intl: '1.2.5',
      moment: '^2.23.0',
      'ng2-charts': '^1.6.0',
      'ng2-ckeditor': '^1.2.7',
      'ngx-ckeditor': '^0.4.0',
      'ngx-color-picker': '^7.2.0',
      'ngx-contextmenu': '^5.1.1',
      'ngx-cookie-service': '^2.1.0',
      'ngx-logger': '^3.3.8',
      'ngx-ui-switch': '^8.1.0',
      'node-sass': '^4.12.0',
      'perfect-scrollbar': '1.4.0',
      'replace-in-file': '^4.2.0',
      rxjs: '^6.3.3',
      'rxjs-compat': '^6.3.3',
      tslib: '^1.9.0',
      'web-animations-js': '^2.3.1',
      'zone.js': '^0.8.26',
    },
    devDependencies: {
      '@angular-devkit/build-angular': '0.12.1',
      '@angular/cli': '^7.1.4',
      '@angular/compiler-cli': '^7.1.4',
      '@angular/language-service': '^7.1.4',
      '@types/jasmine': '3.3.4',
      '@types/node': '~10.12.18',
      '@types/office-js': '^1.0.178',
      codelyzer: '^4.5.0',
      'jasmine-core': '~3.3.0',
      'jasmine-spec-reporter': '~4.2.1',
      karma: '~3.1.4',
      'karma-chrome-launcher': '~2.2.0',
      'karma-cli': '~2.0.0',
      'karma-coverage-istanbul-reporter': '^2.0.4',
      'karma-jasmine': '~2.0.1',
      'karma-jasmine-html-reporter': '^1.4.0',
      protractor: '^5.4.1',
      'ts-node': '~7.0.1',
      tslint: '~5.12.0',
      typescript: '3.1.6',
    },
  },
};
/* tslint:enable */
